Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/CaseIndentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false
